### PR TITLE
platforms/esp32-idf: make the code compile, add build test, cleanup

### PR DESCRIPTION
**Pull request by igrr**
- esp32-idf: Remove unneeded files
- Simplify main.c, remove leftovers from IDF hello-world example
- Sync ESP32 examples for IDF and PIO, check in CI that the source is kept the same
- Add a build job for esp32-idf
- Run the test in QEMU for esp32

### CODE REVIEW

**Comment by vshymanskyy** [comment]
@igrr thanks. I've been working on this already and I got the examples running again.
Unfortunately it's not yet ready to be comitted, as it relies on fix of #24 (which is big)

**Comment by igrr** [comment]
No problem, please ping me when the master branch is fixed, I'll rebase.

**Comment by vshymanskyy** [comment]
@igrr I decided to submit it partially (it's already on the master).
Things to note:
- I have only updated examples for pio
- `d_m3AllocateLinearMemory` flag was removed (now always on)
- `d_m3SkipStackCheck` was enabled for esp devices, will investigate later

**Comment by igrr** [comment]
Thanks, so I understand I need to add `-Dd_m3FixedHeap=8192 -Dd_m3LogOutput=false -Dd_m3SkipStackCheck` to the IDF build as well, right?

**Comment by igrr** [comment]
Okay, have rebased, now this includes the QEMU test.

**Comment by vshymanskyy** [comment]
@igrr esp32 should have enough memory (and proper heap implementation), so should work without `d_m3FixedHeap`

**Comment by vshymanskyy** [comment]
@igrr this is cool, thanks for this contribution. It looks like it's almost ready to be merged, but currently the test timeouts for some reason.
One more thing, when `d_m3LogOutput` is defined, there's no default `Result: ...` output.
Currently you can prin the result like this: https://github.com/wasm3/wasm3/blob/565b585697291a864d127f3cd3c383cebd80ab1e/platforms/esp32-pio/src/main.cpp#L51-L52

**Comment by igrr** [comment]
Yep, the test times out because the app is not finishing (not calling exit or esp_restart). I'll push the fix in a few hours.

About printing the result, i have tried this snippet, but I'm getting an error about dereferencing an incomplete type. Not sure how it compiles in Platformio...

**Comment by vshymanskyy** [comment]
@igrr yeagh, in this case you need:
https://github.com/wasm3/wasm3/blob/565b585697291a864d127f3cd3c383cebd80ab1e/platforms/esp32-pio/src/main.cpp#L14

**Comment by igrr** [comment]
@vshymanskyy Have fixed the test, and also synced IDF and PIO versions of the ESP32 example. The test job will now check that they stay in sync.

**Comment by vshymanskyy** [comment]
Merged :fire: :fire: :fire:

**Comment by vshymanskyy** [comment]
@igrr does standard input work with the ESP32 qemu emulator?
I'm thinking to add `repl` mode to ESP32, then we can try running spec tests suite!

**Comment by igrr** [comment]
It does, sort of. I may need to implement UART FIFO timeout for the IDF UART driver to work properly, but that shouldn't be a big issue.

**Pull request merged**
