### PR TITLE
Build library target with WASI support

### PR DESCRIPTION
**Pull request by saghul**
Fixes: https://github.com/wasm3/wasm3/issues/107

### CODE REVIEW

**Comment by saghul** [comment]
Not sure why the test can fail. Any pointers?

**Comment by vshymanskyy** [comment]
I think that option should be off by default for the library.
Also keep in mind that we have plans to integrate uvwasi (#79), so WASI will no longer be part of `wasm3` core library.

**Comment by saghul** [comment]
Updated defaulting to off.



> Also keep in mind that we have plans to integrate uvwasi (#79), so WASI will no longer be part of `wasm3` core library.
> The existing WASI implementation may be also moved to a separate library.

That's very nice! I guess this doesn't hurt in the interim?

**Comment by vshymanskyy** [comment]
Thanks @saghul ! It's OK, it may take some time until we get to uvwasi ;)

**Comment by saghul** [comment]
Thank you!

**Pull request merged**
