### PR TITLE
Minor changes to m3_GetMemory

### PR DESCRIPTION
**Pull request by robinvanemden**
Deleted `m3_GetMemory()` declaration in `m3_env.h` as there it is also declared (with a slightly different signature) in `m3.h`

Adapted function definition in `m3_env.c` to conform to the remaining `m3.h` function declaration.

(Tested linear memory access by invoking get/set string functions through raw pointer returned by `m3_GetMemory()`: works correctly!)

### CODE REVIEW

**Comment by vshymanskyy** [comment]
The checks failed due to secret token restrictions. No need to fix anything here.

**Comment by robinvanemden** [comment]
Good to know, I wondered about that - thanks!

**Comment by vshymanskyy** [comment]
If you update to master, it should pass all tests

**Comment by robinvanemden** [comment]
> If you update to master, it should pass all tests

Done!

**Pull request merged**
