### PR TITLE
[optimize] Use branchless clz / ctz for x86 (before AVX2 on Intel & ABM+BMI1 on AMD)

### PR DESCRIPTION
**Pull request by MaxGraey**
Compare approaches her:
https://godbolt.org/z/URTGNG

### CODE REVIEW

**Comment by igrr** [comment]
At some point it would be good to make such choices target-specific, or at least introduce target-specific macros to choose one or the other implementation. Point in case, Xtensa:

```
00000000 <clz_old>:
   0:	004136        	entry	a1, 32
   3:	40f220        	nsau	a2, a2
   6:	f01d      	retw.n

00000008 <clz_branchless>:
   8:	004136        	entry	a1, 32
   b:	190c      	movi.n	a9, 1
   d:	208290        	or	a8, a2, a9
  10:	0a0c      	movi.n	a10, 0
  12:	40f880        	nsau	a8, a8
  15:	83a920        	moveqz	a10, a9, a2
  18:	2a8a      	add.n	a2, a10, a8
  1a:	f01d      	retw.n

```

**Comment by MaxGraey** [comment]
@igrr good point! Need more investigation

**Comment by MaxGraey** [comment]
After AVX2 which introduced "lzcnt" instruction this optimization also unnecessary. Last comment fix this

**Comment by soundandform** [comment]
The goal here is improved performance? Have you benchmarked something that makes extensive use of these operations?  

(Speaking to x86 exclusively here.) My experience says there won't be any benefit.  This interpreter is now inherently optimized. The limiting factor seems to be pipeline stalls jumping between operations.  I realized making micro-optimizations to the operations at this point has had effect because it's just using more or less of what would otherwise be dead pipeline cycles.

What's more important seems to be keeping operations small because x86 decodes and stuffs the pipeline on 16-byte intervals.  So, the smaller case might actually win here if it's <= 16 bytes. But, this is totally an (empirical) hunch!

**Comment by MaxGraey** [comment]
That's totally makes sense. I will make some bench.

> more important seems to be keeping operations small because x86 decodes and stuffs the pipeline on 16-byte intervals

If you compare bytecode size here:
https://godbolt.org/z/oFgYRn

clz_old: 27 bytes
clz_branchless: 18 bytes

so it this aspect there's also some advantage

**Comment by MaxGraey** [comment]
Last comment exclude clz / ctz workarounds for PowerPC which defined for zero args
https://godbolt.org/z/nG9xN4

**Comment by MaxGraey** [comment]
Naive microbenchmark results on my machine (MacBook 2019 15-inch, Intel Core i9 2.3 Ghz):
```
================================================================
   Name   |   Dim   |  Total ms |  ns/op  |Baseline| Ops/second
================================================================
clz32_old |   32768 |     0.013 |       0 |      - |2454164170.2
clz64_old |   32768 |     0.022 |       0 |  1.651 |1486077097.5
ctz32_old |   32768 |     0.007 |       0 |  0.548 |4475279978.1
ctz64_old |   32768 |     0.011 |       0 |  0.823 |2983519985.4

clz32_new |   32768 |     0.015 |       0 |  1.108 |2215251487.3
clz64_new |   32768 |     0.011 |       0 |  0.833 |2945438202.2
ctz32_new |   32768 |     0.012 |       0 |  0.920 |2666449670.4
ctz64_new |   32768 |     0.007 |       0 |  0.553 |4438304212.4

clz32_old | 4194304 |     1.704 |       0 |      - |2460882779.2
clz64_old | 4194304 |     2.703 |       0 |  1.586 |1551922168.3
ctz32_old | 4194304 |     0.934 |       0 |  0.548 |4489420549.2
ctz64_old | 4194304 |     1.401 |       0 |  0.822 |2992940625.8

clz32_new | 4194304 |     1.889 |       0 |  1.108 |2220579585.4
clz64_new | 4194304 |     1.422 |       0 |  0.835 |2948782502.6
ctz32_new | 4194304 |     1.600 |       0 |  0.939 |2622011926.4
ctz64_new | 4194304 |     0.934 |       0 |  0.548 |4489218735.6
================================================================
```
Built as `clang++ -Wall -std=c++11 -O3 -o main main.cpp`

Source code: https://repl.it/repls/JealousFairTelecommunications

**Comment by igrr** [comment]
Note that the "Baseline" column value for ctz32_new (0.920) is a bit misleading, since that is relative to clz32_old, not ctz32_old. Compared to ctz32_old, ctz32_new is actually slower.

The 64-bit versions show a nice speed-up though.

**Pull request merged**
