### PR TITLE
Add BUILD_PORTABLE flag to allow building without -march=native

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
I'm fine with either option.

**Comment by axic** [comment]
@vshymanskyy would you consider `BUILD_PORTABLE` or `BUILD_NATIVE` as an option (where by default it would be today's behaviour)?

**Comment by axic** [comment]
> I'm going to add this, however keep in mind that it will have a performance hit (portable wasm3 build can be much slower).

Sure, I'm aware of that 😉

**Comment by axic** [comment]
@vshymanskyy rebased this in case you'd want to consider it.

**Comment by axic** [comment]
Thanks! Could have rebased though if you asked :wink:

**Comment by vshymanskyy** [comment]
It was a small change so I just incorporated it.
Anyway, thanks for your PR!

**Pull request closed without merging**
