### PR TITLE
Use official wapm badge

### PR DESCRIPTION
**Pull request by syrusakbary**
WAPM just added support for package badges (inspired by this repo).

This PR uses the WAPM badge (which will be always up to date) :)

### CODE REVIEW

**Comment by vshymanskyy** [comment]
@syrusakbary icon is missing:
image

**Comment by vshymanskyy** [comment]
This was FF, in Chrome it shows as:
image

**Comment by vshymanskyy** [comment]
@syrusakbary looks good now!

**Comment by vshymanskyy** [comment]
@syrusakbary works on FF now, but not on Chromium...

**Comment by vshymanskyy** [comment]
@syrusakbary after I updated the package, the badge didn't wan to update for quite some time.

You have to set `Cache-Control: no-cache`, according to this:
https://help.github.com/en/github/authenticating-to-github/about-anonymized-image-urls#an-image-that-changed-recently-is-not-updating

**Comment by vshymanskyy** [comment]
shields.io sets such headers:
image

**Comment by syrusakbary** [comment]
Thanks for the ping!

I just fixed it:
```
➜  website git:(master) curl -I https://wapm.io/package/rustpython/badge.svg\?style\=flat
HTTP/2 200
x-powered-by: Express
content-type: image/svg+xml; charset=utf-8
cache-control: no-cache
content-length: 2288
etag: W/"8f0-8afj3UFAXJNmxcveUbJD0EB5xRw"
vary: Accept-Encoding
date: Fri, 31 Jan 2020 06:07:55 GMT
via: 1.1 google
alt-svc: clear
```

**Pull request merged**
